### ISSUE TITLE
Nested loading of yaml files 

### ISSUE THREAD

**Issue by FabianSperrle** [Zipfian-Science/rickled#18]
Hey, I just stumbled upon this project on SO and think it could fit my needs quite well.

From the example on SO and the code I managed to get a basic version running.
Now, I am trying to load nested data structures, e.g. multiple actions associated with a strategy:

strategy.yaml
``` 
action:
  type: from_file
  name: action
  file_path: ./action.yaml
  load_as_rickle: True
  deep: True
  load_lambda: True
````

Python
```
rickle = Rickle('./strategy.yaml', deep=True, load_lambda=True)
rickler = ObjectRickler()
strat: Strategy = rickler.from_rickle(rickle, Strategy)
print(strat.action)
```

This works in the sense that it parses the `action.yaml` file and prints its content. However, I would like to have rickle create an object from that content instead. Is this currently supported?
