### ISSUE TITLE
[FEATURE] Random value

### ISSUE THREAD

**Issue by cuniculus-zipf** [Zipfian-Science/rickled#71]
For mock values, add randoms:

# String
```yaml
key:
  type: random_string
  chars: ABCDE12345
  length: 10
```

# Integer
```yaml
key:
  type: random_integer
  range: 1-10
  seed: 42
```

# Float
```yaml
key:
  type: random_float
  range: 0.0-1.9
```

# List
```yaml
key:
  type: random_list
  values: random_string
  # or values: ['a', 'b', 'c']
  length: 10
  seed: *
```

# Object
```yaml
key:
  type: random_obj
  keys: ['a', 'b']
  # or keys: random_string
  values: random_integer
  # or values: ['a', 'b', 'c']
  min_breadth: 1
  max_breadth: 4
  min_depth: 1
  max_depth: 3
```

# Choice
```yaml
key:
  type: random_choice
  values: ['a', 'b', 'c']
```
